### ISSUE TITLE
ImportError: cannot import name 'check_X_y' from 'sktime.utils.validation'

### ISSUE THREAD

**Issue by philwall3** [uea-machine-learning/sktime-dl#12]
Hi,

the check_X_y is not found in sktime.

```
Traceback (most recent call last):
  File "[censored]", line 13, in <module>
    from sktime_dl.classifiers.deeplearning import CNNClassifier
  File "C:\Users\[censored]\Anaconda3\envs\untitled\lib\site-packages\sktime_dl\classifiers\deeplearning\__init__.py", line 1, in <module>
    from ._cnn import CNNClassifier
  File "C:\Users\[censored]\Anaconda3\envs\untitled\lib\site-packages\sktime_dl\classifiers\deeplearning\_cnn.py", line 23, in <module>
    from sktime.utils.validation import check_X_y
ImportError: cannot import name 'check_X_y' from 'sktime.utils.validation' (C:\Users\[censored]\Anaconda3\envs\untitled\lib\site-packages\sktime\utils\validation\__init__.py)
```

I guess this is supposed to use validate_X_y from https://github.com/alan-turing-institute/sktime/blob/master/sktime/utils/validation/supervised.py ?

**Comment by mloning** [comment]
Hi, thanks for raising the issue. We're working on updating sktime-dl in line with the updates in sktime 0.3.0 (see #11 )!

**Comment by mloning** [comment]
See #13

**Comment by philwall3** [comment]
Thanks for the update! I'll close the issue.
And thanks for the project altogether, it has already helped me a ton!

**Comment by ramdhan1989** [comment]
Hi, did you solve this issue ? I got same problems using sktime 0.4.2
`from sktime.utils.validation import check_X_y
ImportError: cannot import name 'check_X_y'`
please advice,

thank you

**Comment by mloning** [comment]
Hi @ramdhan1989 unfortunately we haven't pushed out a new release for sktime-dl. Any help is appreciated!
